### ISSUE TITLE
Height settings

### ISSUE THREAD

**Issue by darkmall74** [petkivim/embed-google-docs#12]
I am experiencing problems with the height settings for the embedded documents. While using percentage for width, there is no problem, the window size of Google Viewer is perfect. However, I can't seem to achieve the same with height. I simply can't get Viewer to set its display size to the actual length of the given document. I use Purity III as a template (not modified in any way) and I always embed Google Docs into single articles. What am I doing wrong? Is there a way to set the height to dynamic length to adjust it to the actual document?

Here's an example of the code I use:
{google_docs}https://docs.google.com/document/d/1bvQGd7MeL-4AlLPoc6C6HNrnhr6Y0JBHlS1ajzp4drg/pub|width:100%|height:700|border:0{/google_docs}

**Comment by petkivim** [comment]
Probably the map is inside of another HTML element which ```height``` attribute's value is less than 700px and that's why the map's ```height``` attribute 's does not affect the map's height as it should. Could you send the URL of your site so I could take a look at it?

Thanks,
Petteri

**Comment by darkmall74** [comment]
Dear Petteri. Thanks for the quick reply. The site can be found under http://mrblackonline.com and thank you for your help.

**Comment by petkivim** [comment]
Thank you of the crendentials! I took a look at your site and the length of the document in the front page (http://mrblackonline.com/) seems to be correct. At the moment you have defined it in pixels which is the easiest way in this case. When you use percentage for defining ```height``` the value is relative to the parent elements of the document. The problem is that those elements' ```height``` is something else than ```100%```. The easiest solution to embed the whole document without the scroll bar is to set the value of the ```height``` property in pixels based on the document length.

Thanks,
Petteri
