### ISSUE TITLE
Embed problem on my site

### ISSUE THREAD

**Issue by cole81** [petkivim/embed-google-docs#9]
Hello,

Something went wrong and I cannot solve the problem. :( 
Last week there was no problem. So, I embedded some documents but I cannot see the preview of the docs on the website, just links to view them in full screen. (and a part of the source code...)

For example: http://judoinfo.hu/index.php/jcalpro/344-default/348-diak-naptar/2674-regionalis-verseny-budapest-ute

Could you help me? Thanks in advance!

**Comment by petkivim** [comment]
Hi,

Could you please send the code that you're using for embedding the documents? It should look like this:

```
{google_docs}http://judoinfo.hu/images/stories/2017/versenykiirasok/brjsz2017diaktab.pdf{/google_docs}

```

If you have set the base URL ```http://judoinfo.hu/``` it's enough to put the relative path to the document.

```
{google_docs}images/stories/2017/versenykiirasok/brjsz2017diaktab.pdf{/google_docs}
```

Thanks,
Petteri

**Comment by cole81** [comment]
Sure,

{google_docs}/images/stories/2017/versenykiirasok/brjsz2017diaktab.pdf{/google_docs}

I tried the long version: {google_docs}http://judoinfo.hu/images/stories/2017/versenykiirasok/brjsz2017diaktab.pdf{/google_docs} but the result is the same. :(

Maybe the problem is with the JCalPro because when I embed a document in a normal post, it works  well. 
For example: http://judoinfo.hu/index.php/homepage/szakmaiblog/12618-a-letfontossagu-onvedelem-felvezeto-kerdesei

**Comment by petkivim** [comment]
The syntax that you're using is correct. If I understood correctly, the problem occurs only when you try to embed documents inside JCalPro component? If that's the case, then there's a problem with JCalPro. The fact that the plugin works within articles proves that the plugin is compatible with your site. Unfortunately I don't have any experience about JCalPro so I don't know what might cause the issue.

**Comment by petkivim** [comment]
Could you send me the URL of your site so I could a look at it?

Thanks,
Petteri

**Comment by petkivim** [comment]
You sent me the URL of your site regarding another issue so I took a look at your site, but I wasn't able to find embedded documents that are not showing correctly. This means that the code that you're using for embedding the documents is OK and possible occasional problems are caused by Google Docs, e.g. the service does not return the embedded document correctly for some reason. The good news is that you've done everything correctly. The bad news is that there's not much to be done about the occasional problems on Google Doc's side, unfortunately.

Thanks,
Petteri
